// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFSbh-xBPz9zFPV25SekNetZHtQ4YpzgU',
    appId: '1:683788671905:web:6ba7a420e67e2db88149e0',
    messagingSenderId: '683788671905',
    projectId: 'biosafe-d1a94',
    authDomain: 'biosafe-d1a94.firebaseapp.com',
    storageBucket: 'biosafe-d1a94.firebasestorage.app',
    measurementId: 'G-4BV72TDD4D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_pf6_cRe6tUamgkUP0v77piEMM-hBmCY',
    appId: '1:683788671905:android:e69ae939c42d7b698149e0',
    messagingSenderId: '683788671905',
    projectId: 'biosafe-d1a94',
    storageBucket: 'biosafe-d1a94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKTtPfARlH170lADL_hqleC6puAw0TD8s',
    appId: '1:683788671905:ios:2107afc1e7580c788149e0',
    messagingSenderId: '683788671905',
    projectId: 'biosafe-d1a94',
    storageBucket: 'biosafe-d1a94.firebasestorage.app',
    iosBundleId: 'com.example.biosafe',
  );

}